"use strict";

const { allAliasEntries, toTsPaths } = require("../config/aliases");

/**
 * package.json `_moduleAliases` fragment consumed by the `module-alias` package — CJS+JS only.
 * `module-alias/register` (required as the first line of server.js) reads this at process start.
 */
function buildModuleAliasPackageFragment(aliasConfig) {
  return { _moduleAliases: allAliasEntries(aliasConfig) };
}

/**
 * alias-loader.mjs — a small custom ESM loader hook for MJS+JS, where neither `module-alias`
 * (CJS-require-only) nor TypeScript's `paths` (type-checking only, not a runtime mechanism) apply.
 * Registered via `node --experimental-loader=./alias-loader.mjs`. Intercepts only bare `@...`
 * specifiers; everything else passes straight through to Node's normal resolution.
 */
function generateAliasLoaderFile(aliasConfig) {
  const entries = allAliasEntries(aliasConfig);
  const aliasLiteral = JSON.stringify(entries, null, 2);

  return `// Generated by GAZAN. Resolves the project's @-prefixed import aliases for native ESM,
// where neither module-alias (CommonJS-only) nor TypeScript's "paths" (type-checking only) apply.
// Registered via: node --experimental-loader=./alias-loader.mjs
import { fileURLToPath, pathToFileURL } from "node:url";
import path from "node:path";

const ALIASES = ${aliasLiteral};

// Longest target first, so a more specific alias (e.g. "@db") is tried before a shorter one
// that would also match (e.g. the root "@").
const sortedAliases = Object.entries(ALIASES).sort((a, b) => b[1].length - a[1].length);

const projectRoot = fileURLToPath(new URL(".", import.meta.url));

export async function resolve(specifier, context, nextResolve) {
  for (const [alias, dir] of sortedAliases) {
    if (specifier === alias || specifier.startsWith(\`\${alias}/\`)) {
      const rest = specifier.slice(alias.length).replace(/^\\//, "");
      let resolvedPath = path.join(projectRoot, dir, rest);
      // Generated specifiers already carry .js, but resolve defensively for any that don't
      // (native ESM has no extension-guessing of its own).
      if (!path.extname(resolvedPath)) resolvedPath += ".js";
      return nextResolve(pathToFileURL(resolvedPath).href, context);
    }
  }
  return nextResolve(specifier, context);
}
`;
}

/** tsconfig.json paths fragment — merged into the base tsconfig by the tsconfig generator. */
function buildTsconfigAliasFragment(aliasConfig) {
  return toTsPaths(aliasConfig);
}

/**
 * jsconfig.json — plain JS projects get no TypeScript compiler, but VS Code (and most editors)
 * read jsconfig.json for path-alias-aware intellisense/go-to-definition. Purely a DX aid; it has
 * no effect on how the generated project actually runs (module-alias / the MJS loader do that).
 */
function buildJsconfigJson(aliasConfig) {
  const { baseUrl, paths } = toTsPaths(aliasConfig);
  return {
    compilerOptions: {
      baseUrl,
      paths,
    },
    exclude: ["node_modules", "dist"],
  };
}

module.exports = {
  buildModuleAliasPackageFragment,
  generateAliasLoaderFile,
  buildTsconfigAliasFragment,
  buildJsconfigJson,
};
